
/**
 * StudentPocket - Formal Institutional Dispatch Protocol
 * Lead Architect: Sushil Pokhrel
 */
import { ADMIN_EMAIL, CREATOR_NAME, ADMIN_PHONE, SYSTEM_DOMAIN } from '../constants';

export type DispatchType = 
    | 'OTP_REQUEST' 
    | 'VERIFY_REQUEST' 
    | 'VERIFIED_NOTICE' 
    | 'BAN_NOTICE' 
    | 'RESTORE_NOTICE'
    | 'RECOVERY_REQUEST'
    | 'SYSTEM_UPDATE'
    | 'TERMINATION_NOTICE'
    | 'DELETION_NOTICE';

export const emailService = {
    /**
     * Composes a formal letter for institutional communication.
     */
    async sendInstitutionalMail(
        targetUserEmail: string, 
        payload: string, 
        type: DispatchType = 'OTP_REQUEST', 
        username: string = 'Unknown User'
    ): Promise<void> {
        const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
        const upperUser = username.toUpperCase();
        
        let subjectText = "";
        let letterBody = "";

        // Formal Letterhead Components
        const letterhead = `STUDENTPOCKET INSTITUTIONAL REGISTRY\nLocation: ${SYSTEM_DOMAIN}\nContact: ${ADMIN_PHONE}\n------------------------------------------------\n\n`;
        const adminHeader = `TO: ${CREATOR_NAME}\nADMINISTRATION OFFICE\n${ADMIN_EMAIL}\n\n`;
        const dateLine = `DATE: ${date}\n\n`;

        // Handle specific dispatch types for institutional record keeping
        switch (type) {
            case 'OTP_REQUEST':
                subjectText = `Formal Request: Security Access Token for Node ${upperUser}`;
                letterBody = `Dear ${CREATOR_NAME},\n\n` +
                    `This letter is to inform you that a security access token has been requested for the user identity: ${upperUser}.\n\n` +
                    `The following non-sequential authorization code has been generated by the mesh:\n` +
                    `TOKEN: ${payload}\n\n` +
                    `Please ensure this code is relayed securely to the verified communication node: ${targetUserEmail}.\n\n` +
                    `Sincerely,\nStudentPocket Autonomous Security Relay`;
                break;

            case 'VERIFY_REQUEST':
                subjectText = `Institutional Audit: Identity Verification Submission - ${upperUser}`;
                letterBody = `Dear ${CREATOR_NAME},\n\n` +
                    `I am writing to submit an official request for identity verification on behalf of the student node: ${upperUser}.\n\n` +
                    `The user has completed the biometric intake and is now awaiting your professional audit. You may review the credentials and authorize the node using the following link:\n` +
                    `AUDIT LINK: ${window.location.origin}/?v=${payload}\n\n` +
                    `Please review this submission at your earliest convenience to maintain mesh integrity.\n\n` +
                    `Best Regards,\nInstitutional Intake Department`;
                break;

            case 'RECOVERY_REQUEST':
                subjectText = `Security Appeal: Access Restoration Request - ${upperUser}`;
                letterBody = `Dear ${CREATOR_NAME},\n\n` +
                    `An official appeal for account restoration has been filed by the user: ${upperUser}.\n\n` +
                    `This node was previously restricted due to detected protocol violations. The user has submitted a formal recovery form for your review. You can access the secure recovery terminal here:\n` +
                    `RECOVERY TERMINAL: ${window.location.origin}/?recovery=${payload}\n\n` +
                    `Your final decision as the Master Architect is required to reinstate this node.\n\n` +
                    `Respectfully,\nMesh Recovery Protocol`;
                break;

            case 'VERIFIED_NOTICE':
                subjectText = `Official Notification: Identity Verification Successful`;
                letterBody = `Dear ${upperUser},\n\n` +
                    `On behalf of the Lead Architect ${CREATOR_NAME}, I am pleased to inform you that your institutional identity has been successfully verified.\n\n` +
                    `Your node is now fully synchronized with the StudentPocket mesh. You have been granted Platinum Clearance, unlocking all secure data features.\n\n` +
                    `Should you require further assistance, please contact the admin office at ${ADMIN_PHONE}.\n\n` +
                    `Regards,\nOffice of the Lead Architect`;
                break;

            case 'BAN_NOTICE':
                subjectText = `Notice of Protocol Violation: Account Restriction`;
                letterBody = `Dear ${upperUser},\n\n` +
                    `We regret to inform you that your access to StudentPocket has been restricted effective immediately.\n\n` +
                    `Reason for restriction: ${payload}\n\n` +
                    `If you believe this action was taken in error, you may file a formal Access Recovery Form via the system login terminal. Your appeal will be reviewed personally by ${CREATOR_NAME}.\n\n` +
                    `System Security Node,\nStudentPocket Mesh`;
                break;
            
            case 'SYSTEM_UPDATE':
                subjectText = `Institutional Alert: System Protocol Update`;
                letterBody = `Announcement Payload:\n${payload}`;
                break;

            case 'TERMINATION_NOTICE':
                subjectText = `Critical Notice: Identity Node Termination - ${upperUser}`;
                letterBody = `Action Detail: ${payload}`;
                break;

            case 'DELETION_NOTICE':
                subjectText = `Security Protocol: Data Deletion Notice - ${upperUser}`;
                letterBody = `Action Detail: ${payload}`;
                break;
        }

        const fullContent = letterhead + adminHeader + dateLine + letterBody;
        const mailtoLink = `mailto:${ADMIN_EMAIL}?subject=${encodeURIComponent(subjectText)}&body=${encodeURIComponent(fullContent)}`;
        
        window.location.href = mailtoLink;
    }
};
